[package]
name = "parquet-explorer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "4.3.0"
parquet = "4.3.0"
clap = "3.0.0-beta.2"
datafusion = "4.0.0"
tokio = "1.7.1"